CREATE TABLE IF NOT EXISTS loan_applications
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    amount numeric(15,2) NOT NULL,
    term integer NOT NULL,
    email character varying(150) NOT NULL,
    id_loan_application_status bigint NOT NULL,
    id_loan_type bigint NOT NULL,
    CONSTRAINT loan_applications_pkey PRIMARY KEY (id),
    CONSTRAINT fk_loan_applications_loan_type_id FOREIGN KEY (id_loan_type)
        REFERENCES loan_type (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT fk_loan_applications_loan_application_status_id FOREIGN KEY (id_loan_application_status)
            REFERENCES loan_application_status (id) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE NO ACTION
            NOT VALID
);

CREATE TABLE IF NOT EXISTS loan_application_status
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    description character varying(100),
    CONSTRAINT loan_application_status_pkey PRIMARY KEY (id),
    CONSTRAINT loan_application_status_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS loan_types
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) NOT NULL,
    minimum_amount numeric(15,2) NOT NULL,
    maximum_amount numeric(15,2) NOT NULL,
    interest_rate numeric NOT NULL,
    automatic_validation character varying(50) ,
    CONSTRAINT loan_types_pkey PRIMARY KEY (id),
    CONSTRAINT loan_types_name_key UNIQUE (name)
);