spring:
  application:
    name: pragma-ms-solicitudes
    api-key: mi-api-key-secreta
  profiles:
    include: r2dbc, rest-consumer, sqs-sender

logging:
  level:
    co.com.pragma: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui.html
