server:
  port: 8081

spring:
  application:
    name: "pragma-ms-solicitudes"
  profiles:
    include: r2dbc

logging:
  level:
    co.com.pragma: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
