spring:
  application:
    name: pragma-ms-solicitudes
  profiles:
    include: r2dbc, rest-consumer

logging:
  level:
    co.com.pragma: DEBUG

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html